service: sirib

image: vonchristian/sirib

servers:
  web:
    hosts:
      - 146.190.83.79
    env:
      clear:
        RAILS_MAX_THREADS: 2
  job:
    hosts:
      - 146.190.83.79
    cmd: bin/jobs
    env:
      clear:
        RAILS_MAX_THREADS: 5

proxy:
  ssl: false

registry:
  username: vonchristian
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - SIRIB_DATABASE_PASSWORD
  clear:
    WEB_CONCURRENCY: 0
    JOB_CONCURRENCY: 1
    RUBY_GC_HEAP_GROWTH_FACTOR: 1.02
    RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR: 2

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "sirib_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

accessories:
  db:
    image: postgres:17
    host: 146.190.83.79
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: sirib
        POSTGRES_DB: sirib_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
